// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Mithril = require("mithril");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var MDom = /* module */[];

var MComponent = /* module */[];

var ReasonMithril = /* module */[];

var MEvent = /* module */[];

function onClickHandler($$event) {
  console.log($$event.srcElement);
  return /* () */0;
}

var props = {
  type: "message",
  "aria-label": "hello inaria",
  onclick: onClickHandler
};

var component = Mithril.m("div", props, /* array */[
      "Hello World from mithril",
      Mithril.m("span", undefined, "senthil- Mithril bindings")
    ]);

console.log(component);

var HelloComponent = /* module */[
  /* onClickHandler */onClickHandler,
  /* props */props,
  /* component */component
];

Mithril.render(Caml_option.nullable_to_opt(document.getElementById("root")), component);

var myDiv = /* () */0;

exports.MDom = MDom;
exports.MComponent = MComponent;
exports.ReasonMithril = ReasonMithril;
exports.MEvent = MEvent;
exports.HelloComponent = HelloComponent;
exports.myDiv = myDiv;
/* component Not a pure module */
