// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Redom = require("redom");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var ReasonRedom = /* module */[];

var stateInstance = {
  age: 45
};

var child = Redom.el("div", undefined, String(stateInstance.age));

child.addEventListener("build", (function ($$event) {
        child.textContent = $$event.detail;
        console.log($$event.detail);
        return /* () */0;
      }), false);

function onClickHandler(param) {
  var currentAge = stateInstance.age;
  stateInstance.age = currentAge + 1 | 0;
  var updateTextEvent = new CustomEvent("build", {
        detail: String(stateInstance.age)
      });
  child.dispatchEvent(updateTextEvent);
  return /* () */0;
}

var elmentToRender = Redom.el("button", {
      "data-id": 5,
      onclick: onClickHandler
    }, /* array */[
      "Hello World",
      child
    ]);

function component(param) {
  return elmentToRender;
}

var HelloComponent = /* module */[
  /* stateInstance */stateInstance,
  /* child */child,
  /* onClickHandler */onClickHandler,
  /* elmentToRender */elmentToRender,
  /* component */component
];

Redom.mount(Caml_option.nullable_to_opt(document.getElementById("root")), elmentToRender);

var myDiv = /* () */0;

exports.ReasonRedom = ReasonRedom;
exports.HelloComponent = HelloComponent;
exports.myDiv = myDiv;
/* child Not a pure module */
