// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Redom = require("redom");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var ReasonRedom = /* module */[];

function onClickHandler($$event) {
  console.log($$event);
  return /* () */0;
}

var component = Redom.el("div", {
      "data-id": 5,
      onclick: onClickHandler
    }, /* array */[
      "Hello World",
      Redom.el("span", undefined, "senthil")
    ]);

var HelloComponent = /* module */[
  /* onClickHandler */onClickHandler,
  /* component */component
];

Redom.mount(Caml_option.nullable_to_opt(document.getElementById("root")), component);

var myDiv = /* () */0;

exports.ReasonRedom = ReasonRedom;
exports.HelloComponent = HelloComponent;
exports.myDiv = myDiv;
/* component Not a pure module */
